kind: Deployment
apiVersion: apps/v1
metadata:
   name: aksproject
spec:
   replicas: 2
   selector:      # tells the controller which pods to take under control
    matchLabels:
     app: aksproject
   template:
      metadata:
        labels:
          app: aksproject
      spec:
       containers:
        - name: aksproject
          image: devops7k/project_pipeline
          imagePullPolicy: Always
          ports:
          - containerPort: 90
