kind: Deployment
apiVersion: apps/v1
metadata:
   name: aksproject1
spec:
   replicas: 2
   selector:      # tells the controller which pods to take under control
    matchLabels:
     app: aksproject1
   template:
      metadata:
        labels:
          app: aksproject1
      spec:
       containers:
        - name: aksproject1
          image: devops7k/project_pipeline
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          
          
          
# #      --------------------------
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#    name: cloudknowledges
# spec: 
#    selector:
#        matchLabels:
#             app: cloudknowledges       
#    replicas: 2
#    strategy:
#        type: RollingUpdate
#        rollingUpdate: 
#           maxSurge: 1
#           maxUnavailable: 1
#    template:
#        metadata: 
#           labels:
#             app: cloudknowledges
#        spec: 
#           containes:
#              - name: cloudknowledges
#                image: devops7k/project_pipeline
#                imagePullPolicy: Always
#                ports: 
#                   - containerPort: 80
          
   
