kind: Service                             
apiVersion: v1
metadata:
  name: aksproject
  labels:
    app: aksproject
spec:
  ports:
    - port: 8080                               
      targetPort: 8080                    
      nodePort: 30007
      protocol: TCP
  selector:
    app: aksproject                    
  type: LoadBalancer    
#   ---------------------


#   -------------------------------
# kind: Service
# apiVersion: v1
# metadata:
#   name: cloudknowledges
#   labels:
#      app: cloudknowledges
# spec:
#    selector: 
#      app: cloudknowledges
#    type: LoadBalancer
#    ports:
#      - port: 8080
#        targetPort: 80
#        nodePort: 31200

