# kind: Service                             
# apiVersion: v1
# metadata:
#   name: aksproject
#   labels:
#     app: aksproject
# spec:
#   ports:
#     - port: 8080                               
#       targetPort: 80                    
#       nodePort: 30000
#   selector:
#     app: aksproject                    
#   type: LoadBalancer    
  
#   -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: cloudknowledges
  labels:
     app: cloudknowledges
spec:
   selector: 
     app: cloudknowledges
   type: LoadBalancer
   ports:
     - port: 8080
       targetPort: 80
       nodePort: 31200

