kind: Service                             
apiVersion: v1
metadata:
  name: aksproject1
  labels:
    app: aksproject1
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: aksproject1                    
  type: LoadBalancer    
  
#   -------------------------------
# kind: Service
# apiVersion: v1
# metadata:
#   name: cloudknowledges
#   labels:
#      app: cloudknowledges
# spec:
#    selector: 
#      app: cloudknowledges
#    type: LoadBalancer
#    ports:
#      - port: 8080
#        targetPort: 80
#        nodePort: 31200

