kind: Service                             
apiVersion: v1
metadata:
  name: aksproject
  labels:
    app: aksproject
spec:
  ports:
    - port: 8090                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: aksproject                    
  type: LoadBalancer                   
