kind: Service                             
apiVersion: v1
metadata:
  name: aks_project
  labels:
    app: aks_project
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: aks_project                    
  type: LoadBalancer                   